In [4]:
import time
import numpy as np

matrix = [[1, 2, 3, 4, 5, 6, 7, 8, 9], 
          [1, 2, 3, 4, 5, 6, 7, 8, 9],
          [1, 2, 3, 4, 5, 6, 7, 8, 9],
          [1, 2, 3, 4, 5, 6, 7, 8, 9],
          [1, 2, 3, 4, 5, 6, 7, 8, 9],
          [1, 2, 3, 4, 5, 6, 7, 8, 9],
          [1, 2, 3, 4, 5, 6, 7, 8, 9],
          [1, 2, 3, 4, 5, 6, 7, 8, 9],
          [1, 2, 3, 4, 5, 6, 7, 8, 9]]

matrix_1 = [[1, -2, 3],
            [4, 0, 6],
            [-7, 8, 9]]

matrix_2 = [[2, 3, 0, 5], 
            [4, -3, -1, 1],
            [2, 5, 1, 3],
            [2, 7, 2, -2]]


m_1 = [[1, 2, 3, 4, 5]]

m_2 = [[1],
       [2],
       [3],
       [4],
       [5]]

def lead_time(function):
    def wrapped(*args):
        start_time = time.perf_counter_ns()
        res = function(*args)
        print(f"lead_time {function.__name__}: {time.perf_counter_ns() - start_time}")
        return res
    return wrapped  



In [5]:
@lead_time
def py_matmul(a: list, b: list):
    c = [[0 for i in range(len(b[0]))] for j in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                c[i][j] += a[i][k] * b[k][j]
    return c

@lead_time
def np_matmul(a, b):
    return np.matmul(a, b)

summ = 0
@lead_time
def py_det(a):
    return py_det_recurs(a)

def py_det_recurs(a: list) -> float:
    n = len(a)
    summ = 0.
    if n >= 3 :
        for k in range(1, n+1):
            b = [
                row[:k - 1] + row[k:] 
                for row in a[1:]
            ]
            summ += ((-1) ** (k + 1)) * a[0][k-1] * py_det_recurs(b)
        return summ
    else:
        summ += a[0][0] * a[1][1] - a[0][1] * a[1][0]
        return summ

@lead_time
def np_det(a):
    return np.linalg.det(a)

@lead_time
def py_transpose(a):
    i, j = 0, 0
    c = [[0 for i in range(len(a))] for j in range(len(a[0]))]
    for i in range(len(a)):
        for j in range(len(a[0])):
            c[j][i] = a[i][j]
    return c

@lead_time
def np_transpose(a):
    return np.transpose(a)

@lead_time
@lead_time
def py_matmul(a: list, b: list):
    c = [[0 for i in range(len(b[0]))] for j in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                c[i][j] += a[i][k] * b[k][j]
    return c

@lead_time
def np_matmul(a, b):
    return np.matmul(a, b)

summ = 0
@lead_time
def py_det(a):
    return py_det_recurs(a)

def py_det_recurs(a: list) -> float:
    n = len(a)
    summ = 0.
    if n >= 3 :
        for k in range(1, n+1):
            b = [
                row[:k - 1] + row[k:] 
                for row in a[1:]
            ]
            summ += ((-1) ** (k + 1)) * a[0][k-1] * py_det_recurs(b)
        return summ
    else:
        summ += a[0][0] * a[1][1] - a[0][1] * a[1][0]
        return summ

@lead_time
def np_det(a):
    return np.linalg.det(a)

@lead_time
def py_transpose(a):
    i, j = 0, 0
    c = [[0 for i in range(len(a))] for j in range(len(a[0]))]
    for i in range(len(a)):
        for j in range(len(a[0])):
            c[j][i] = a[i][j]
    return c

@lead_time
def np_transpose(a):
    return np.transpose(a)

#I tried using the widget Blackbox AI and this COOOOL!!!
#Использовал метод окаймляющих миноров, но стер случайно, оно использует метод Гаусса 

@lead_time
def py_find_rank(matrix):
  """Finds the rank of a matrix.

  Args:
    matrix: The matrix to find the rank of.

  Returns:
    The rank of the matrix.
  """

  # Check if the matrix is empty.

  if not matrix:
    return 0

  # Check if the matrix is a square matrix.

  if len(matrix) != len(matrix[0]):
    raise ValueError("Matrix must be square.")

  # Initialize the rank to 0.

  rank = 0

  # Iterate over the columns of the matrix.

  for column in range(len(matrix[0])):

    # Find the pivot element in the column.

    pivot_element = matrix[0][column]

    # If the pivot element is zero, then the matrix is not full rank.

    if pivot_element == 0:
      return rank

    # Eliminate all elements below the pivot element.

    for row in range(1, len(matrix)):
      multiplier = matrix[row][column] / pivot_element
      for column_index in range(len(matrix[row])):
        matrix[row][column_index] -= multiplier * matrix[0][column_index]

    # Increment the rank.

    rank += 1

  return rank

@lead_time
def np_find_rank(matrix):
    return np.linalg.matrix_rank(matrix)


In [6]:

print(py_matmul(m_2, m_1))
print(np_matmul(m_2, m_1))
print(py_det(matrix_2))
print(np_det(matrix_2))
print(py_transpose(m_2))
print(np_transpose(m_2))
print(py_find_rank(matrix_1))
print(np_find_rank(matrix_1))

lead_time py_matmul: 61400
lead_time wrapped: 343400
[[1, 2, 3, 4, 5], [2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [5, 10, 15, 20, 25]]
lead_time np_matmul: 60300
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
lead_time py_det: 96000
42.0
lead_time np_det: 177700
42.00000000000004
lead_time py_transpose: 19200
[[1, 2, 3, 4, 5]]
lead_time np_transpose: 34500
[[1 2 3 4 5]]
lead_time py_find_rank: 25300
3
lead_time np_find_rank: 274300
3
